name: trangbong
services:
  api-gateway:
    build:
      context: ../services/api-gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
      - "9090"
  identity-service:
    build:
      context: ../services/identity-service
    expose:
      - "8080"
      - "9090"
  customer-service:
    build:
      context: ../services/customer-service
    expose:
      - "8080"
      - "9090"
  artist-service:
    build:
      context: ../services/artist-service
    expose:
      - "8080"
      - "9090"
  catalog-service:
    build:
      context: ../services/catalog-service
    expose:
      - "8080"
      - "9090"
  scheduling-service:
    build:
      context: ../services/scheduling-service
    expose:
      - "8080"
      - "9090"
  booking-service:
    build:
      context: ../services/booking-service
    expose:
      - "8080"
      - "9090"
  payment-service:
    build:
      context: ../services/payment-service
    expose:
      - "8080"
      - "9090"
  notification-service:
    build:
      context: ../services/notification-service
    expose:
      - "8080"
      - "9090"
  fengshui-service:
    build:
      context: ../services/fengshui-service
    expose:
      - "8080"
      - "9090"
  consultation-service:
    build:
      context: ../services/consultation-service
    expose:
      - "8080"
      - "9090"
  analytics-service:
    build:
      context: ../services/analytics-service
    expose:
      - "8080"
      - "9090"

